name: Trello Stalk Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: node index.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add board_state.json
          git diff --cached --quiet || git commit -m "update board state [skip ci]" && git push